### ISSUE TITLE
Source in pypi!

### ISSUE THREAD

**Issue by paugier** [fleming79/readim#1]
Hello,

I compiled without any problem on linux (debian jessie) by cloning the git repository. But it seems to me that it would have worked the same with pip if the source were in pypi.

Now there is only a window wheel which is not useful for linux users.

Can you please submit the source to pypi?

Moreover, I was confused when I read your README file. I didn't understood that the  C++ library provided by LaVision GMBH was included in the source. I looked for this library on the web and didn't manage to get it. You could modify the README file to be clearer, for example like this:

```
ReadIM is a Python package to read and write DaVis Images and Vectors DaVis V8.
It contains C++ libraries provided by `LaVision GMBH <http://www.lavision.de/en/>`_ 
and a low level interface wrapper for Python.
```

Thank you for this tool, which seems to work fine for what I need to do with im7 files!

**Comment by fleming79** [comment]
Thanks for your feedback. I've added the source to pypi.
