### ISSUE TITLE
pip from pypi fails on Mac OS X

### ISSUE THREAD

**Issue by alexlib** [fleming79/readim#3]
Thanks for fixing the swig issue

Now I run 

`pip uninstall readim`
`pip install readim` 
and it fails with the error of compilation - not finding `ReadIMx.h`

if I run 
`pip install git+https://bitbucket.org/fleming79/readim` 
All works fine. 

Not sure but it seems to be the binary wheel that you provided.

**Comment by fleming79** [comment]
Thanks Alex, missing header files now included in the source distribution.

**Comment by alexlib** [comment]
confirm it works now.
